[theme]
primaryColor = "#7C3AED"
backgroundColor = "#F7F7FB"
secondaryBackgroundColor = "#ffffff"
textColor = "#171423"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
